data_collection/forms.py
from data_collection.models import *
from django.forms.extras.widgets import SelectDateWidget
from django import forms
from django.forms import ModelForm, Form, HiddenInput, TextInput, Select, BaseFormSet
import datetime
from bootstrap3_datetime.widgets import DateTimePicker
from django.utils.safestring import mark_safe
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Div

YES_NO = [(True, "Yes"), (False, "No")]

class NewFieldtripForm(Form):
    location = forms.ModelChoiceField(widget=forms.Select(attrs={'class': 'select form-control'}), queryset=Location.objects.none(),label='Location')
    beginfieldtrip = forms.ChoiceField(widget=DateTimePicker(options={"format": "YYYY-MM-DD HH:mm"}),
                                       label='Trip Start')
    endfieldtrip = forms.ChoiceField(widget=DateTimePicker(options={"format": "YYYY-MM-DD HH:mm"}),
                                     label='Trip End')
    workers = forms.ModelMultipleChoiceField(queryset=Worker.objects.none(),
                                             widget=forms.CheckboxSelectMultiple,
                                             label='Field Team',
                                             required=False)
    note = forms.CharField(label='Note',
                           required=False,
                           widget=forms.Textarea)
    def __init__(self, *args, **kwargs):
        workers = kwargs.pop('workers', Worker.objects.none())
        super(NewFieldtripForm, self).__init__(*args, **kwargs)
        self.fields['location'].queryset = Location.objects.filter(active=1).filter(locationtype='field trip')
        self.fields['workers'].queryset = workers
    def clean(self):
        cleaned_data = super(NewFieldtripForm, self).clean()
        beginfieldtrip = cleaned_data.get('beginfieldtrip')
        endfieldtrip = cleaned_data.get('endfieldtrip')
        if beginfieldtrip and endfieldtrip:
            if endfieldtrip < beginfieldtrip:
                raise forms.ValidationError(
                "You can't start a trip before you end it!"
                )


class WorkerForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super (WorkerForm, self).__init__(*args, **kwargs)
    class Meta:
        model = Worker
        fields = ['idworker','workername','workertype','affiliation','jobtitle','active','email','phonenumber']
        labels = {
            'workername': ('Name'),
            'workertype': ('Work type'),
            'affiliation': ('Primary affiliation'),
            'jobtitle': ('Job Title'),
            'active': ('Currently active'),
            'email': ('E-mail'),
            'phonenumber': ('Phone number'),
            }
        widgets = {
            'active': Select(choices=YES_NO),
            'idworker': TextInput(attrs={'readonly':'readonly'}),
            }

class ExistingWorkerForm(Form):
    existing_workers = forms.ModelChoiceField(queryset=Worker.objects.all(),label='Modify existing profile')
    def __init__(self, *args, **kwargs):
        super (ExistingWorkerForm, self).__init__(*args, **kwargs)


class SitesForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super (SitesForm, self).__init__(*args, **kwargs)
    class Meta:
        model = Site
        fields = ['site','location','sitetype','xlocation','ylocation','sitecode','note','active']
        labels = {
            'site': ('Site Name'),
            'location': ('Location'),
            'sitetype': ('Site type'),
            'xlocation': ('Easting (UTM Zone 55N)'),
            'ylocation': ('Northing (UTM Zone 55N)'),
            'sitecode': ('Site Code (3-5 letters all caps)'),
            'note': ('Note'),
            'active': ('Currently Active')
            }


class SelectWaterSampleSiteForm(Form):
    selected_sites = forms.ModelMultipleChoiceField(queryset=Site.objects.none(),widget=forms.CheckboxSelectMultiple)
    def __init__(self, *args, **kwargs):
        filtered_sites = kwargs.pop('filtered_sites', Site.objects.none())
        super(SelectWaterSampleSiteForm, self).__init__(*args, **kwargs)
        self.fields['selected_sites'].queryset = filtered_sites


class SamplenamemasterlistForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super (SamplenamemasterlistForm, self).__init__(*args, **kwargs)
    class Meta:
        model = Samplenamemasterlist
        fields = ['samplename','sampletype']


class GroundwatersampledetailsForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super (GroundwatersampledetailsForm, self).__init__(*args, **kwargs)
    class Meta:
        model = Groundwatersampledetails
        fields = ['samplename','site','idfieldtrip']

class CavedripwaterForm(Form):
    bottle_down_day = forms.ChoiceField(choices=())
    bottle_down_time = forms.DateTimeField(required=False, widget=DateTimePicker(options={"format": "HH:mm"}, icon_attrs={'class': 'glyphicon glyphicon-time'}),label = 'Time')
    initialmass = forms.DecimalField(label='Initial Mass')
    bottle_up_day = forms.ChoiceField(choices=())
    bottle_up_time = forms.DateTimeField(required=False, widget=DateTimePicker(options={"format": "HH:mm"}, icon_attrs={'class': 'glyphicon glyphicon-time'}), label = 'Time')
    finalmass = forms.DecimalField(label='Final Mass')
    watersamplename = forms.CharField(widget=HiddenInput())
    dripcount_day = forms.ChoiceField(choices=())
    dripcount_time = forms.DateTimeField(required=False, widget=DateTimePicker(options={"format": "HH:mm"}, icon_attrs={'class': 'glyphicon glyphicon-time'}),label = 'Time')
    dripcount_1 = forms.IntegerField(label='Drip Count 1')
    dripcount_2 = forms.IntegerField(label='Drip Count 2')
    dripcount_3 = forms.IntegerField(label='Drip Count 3')
    fieldinstrumentname = forms.ModelChoiceField(queryset=())
    orp = forms.DecimalField(label='ORP')
    tds = forms.DecimalField(label='TDS')
    conductivity = forms.DecimalField(label='TDS')
    ph = forms.DecimalField(label='pH')
    temp = forms.DecimalField(label='Temperature')
    def __init__(self, *args, **kwargs):
        day_choices = kwargs.pop('day_choices', None)
        flag = kwargs.pop('trip_length_flag', None)
        initialmass = kwargs.pop('initialmass', None)
        watersamplename = kwargs.pop('watersamplename', None)
        super(CavedripwaterForm, self).__init__(*args, **kwargs)
        self.fields['fieldinstrumentname'].queryset = Fieldinstrumentname.objects.filter(fieldinstrumenttype='Ultrameter')
        if day_choices is not None and flag == 0:
            self.fields['bottle_down_day'].choices = day_choices
            self.fields['bottle_up_day'].choices = day_choices
            self.fields['dripcount_day'].choices = day_choices
        elif day_choices is not None:
            self.fields['bottle_down_day'].choices = day_choices
            self.fields['bottle_up_day'].choices = day_choices
            self.fields['bottle_down_day'].widget = HiddenInput()
            self.fields['bottle_up_day'].widget = HiddenInput()
        if initialmass is not None:
            self.fields['initialmass'].initial = initialmass
        if watersamplename is not None:
            # self.fields['watersamplename'].queryset = Samplenamemasterlist.objects.filter(samplename=watersamplename)
            self.fields['watersamplename'].initial = watersamplename
    note = forms.CharField(label='Note')

class DripcollectionbottleSubmitForm(ModelForm):
    class Meta:
        model = Dripcollectionbottle
        fields = ['samplename','initialmass', 'finalmass', 'deploytime',
                  'collecttime','note']


class DripintervalForm(ModelForm):
    def __init__(self, *args, **kwargs):
        site = kwargs.pop('site', Site.objects.none())
        idfieldtrip = kwargs.pop('idfieldtrip', Fieldtrip.objects.none())
        super(DripintervalForm, self).__init__(*args, **kwargs)
        self.fields['site'].queryset = Site.objects.filter(site = site)
        self.fields['idfieldtrip'].queryset = Fieldtrip.objects.filter(idfieldtrip = idfieldtrip)
    class Meta:
        model = Dripinterval
        fields = ['site','idfieldtrip','timecollected','count1', 'count2', 'count3']
        labels = {
            'timecollected': ('Time Drip Count Measured'),
            'count1': ('Drip Count Measurement 1'),
            'count2': ('Drip Count Measurement 2'),
            'count3': ('Drip Count Measurement 3'),
            }
        widgets = {
            'site': HiddenInput(),
            'idfieldtrip': HiddenInput(),
            'timecollected': DateTimePicker(options={"format": "YYYY-MM-DD HH:mm"})
            }

class PlatecollectForm(ModelForm):
    def __init__(self, *args, **kwargs):
        idfieldtrip = kwargs.pop('idfieldtrip', Fieldtrip.objects.none())
        super(PlatecollectForm, self).__init__(*args, **kwargs)
        self.fields['collectfieldtrip'].queryset = Fieldtrip.objects.filter(idfieldtrip = idfieldtrip)
    class Meta:
        model = Platefielddata
        fields = ['samplename','datedeploy','datecollect','collectfieldtrip']
        labels = {
            'samplename': ('Collected Plate Name'),
            'datedeploy': ('Date Deployed'),
            'datecollect': ('Date Plate Collected'),
            }
        widgets = {
            'samplename': TextInput(attrs={'readonly':'readonly'}),
            'datedeploy': TextInput(attrs={'readonly':'readonly'}),
            'collectfieldtrip': HiddenInput(),
            'datecollect': DateTimePicker(options={"format": "YYYY-MM-DD HH:mm"}),
            }

class PlatedeplyForm(ModelForm):
    def __init__(self, *args, **kwargs):
        site = kwargs.pop('site', Site.objects.none())
        idfieldtrip = kwargs.pop('idfieldtrip', Fieldtrip.objects.none())
        super(PlatedeplyForm, self).__init__(*args, **kwargs)
        self.fields['site'].queryset = Site.objects.filter(site = site)

data_collection/templates/alk.html
{% extends 'layouts/base.html' %}
{% block title %}Enter - {{ block.super }}{% endblock %}
{% block content %}
<form action="/alk/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

data_collection/templates/download_data.html
{% extends 'layouts/base.html' %}
{% block title %}Download - {{ block.super }}{% endblock %}
{% block content %}
  <h1>Sucka</h1>
  <button type="button">There's nothing to do</button>
{% endblock %}

data_collection/templates/enter_data.html
{% extends 'layouts/base.html' %}
{% block title %}Download - {{ block.super }}{% endblock %}
{% block content %}
  <a href="new_fieldtrip.html">New Field Trip</a>
  <a href="new_fieldtrip.html">Work on in progress field trip data entry</a>
  <a href="new_fieldtrip.html">Results of Lab Measurements</a>
  <a href="new_fieldtrip.html">New Field Trip</a>

{% endblock %}

data_collection/templates/enter_site_data.html
{% extends 'layouts/base.html' %}
{% block title %}Enter - {{ block.super }}{% endblock %}
{% block content %}
{% load data_collection_tags %}
<head>
<h2>{{ site }} - {{ watersamplename }}</h2>
</head>
<form action="/enter-site-data/" method="post">
    {% csrf_token %}
    <h4>Drip Collection Bottle:</h4>
    {{ tmp_form.as_p }}
    <h4>Plate Collection:</h4>
    {{ platecollect_form }}
    <h4>Plate Deployment:</h4>
    {{ platedeploy_form }}
    <h4>Samples Collected:</h4>
    {{ collectedsamples_formset.management_form }}
      {% for form in collectedsamples_formset %}
      <div class="hideInputs">
      <!-- {% autoescape off %}
        <h5>{{ analysis_display|get:form.intendedanalysis.value }}</h5>
      {% endautoescape %} -->
        {{ form.as_p }}
      </div>
      {% endfor %}
    </div>
    <input type="submit" value="Submit" id="submit"/>
</form>
<div class="hidden" id="outside-form" />
<script>
  $(function() {
    var $formsetTotal = $('id_form-TOTAL_FORMS');
    var multiforms_are_stupid_regex = /id_form-\d+/gi;
    var multiforms_are_stupid_replacement = "id_form-"
    $( ".hideInputs" ).each(function(){
      var $parent = $(this);
      var $toHide = $parent.children(":not(h5)");

      var $title = $parent.find('h5');
      var $cb = $("<input type='checkbox' />");

      $cb.on('change', function(){
        if(this.checked) {
          $parent.addClass('filled');
          $toHide.detach().appendTo($parent);
        } else {
          $parent.removeClass('filled');
          $toHide.detach().appendTo("#outside-form");
        }
      }).trigger('change');

      $cb.prependTo($title);
    });

    $('#submit').on('click', function(){
      var $inputs = $( ".hideInputs.filled" )
      $inputs.each(function(idx){
        $(this).html($(this).html(multiforms_are_stupid_regex, multiforms_are_stupid_replacement + idx));
      });

      $formsetTotal.val($inputs.length());
    });
  });
  </script>
{% endblock %}

data_collection/templates/field_instruments.html
{% extends 'layouts/base.html' %}
{% block title %}Enter - {{ block.super }}{% endblock %}
{% block content %}
<form action="/new-fieldtrip/field-instruments" method="post">
  <h4>Gas Sampling and Measurements:</h4>
    {% csrf_token %}
    <h4>CO<sub>2</sub> Spot Check:</h4>
    {{ spotcheck_formset.management_form }}
      {% for form in spotcheck_formset %}
      <div>
        {{ form }}
      </div>
      {% endfor %}
    </div>
  {{ upload_form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

data_collection/templates/index.html
{% extends 'layouts/base.html' %}
{% block title %}Homepage - {{ block.super }}{% endblock %}
{% block content %}
  <img src="/static/images/crab.gif" alt="jet fuel cant melt steel beams" style="width:304px;height:228px;">
{% endblock %}

data_collection/templates/lines.html
{% extends 'layouts/base.html' %}
{% block title %}Enter - {{ block.super }}{% endblock %}
{% block content %}
{% load data_collection_tags %}
<form action="/lines/" method="post">
    {% csrf_token %}
{% endblock %}

data_collection/templates/new_fieldtrip.html
{% extends 'layouts/base.html' %}
{% block title %}Enter - {{ block.super }}{% endblock %}
{% block content %}
{% load bootstrap3 %}

<form action="/new-fieldtrip/" method="post">
 {{ trip_form.non_field_errors }}
 {% csrf_token %}
 <div class="container">
    <div class="row">
      <div class="col-md-3">
        {% bootstrap_field trip_form.location %}
      </div>
      <div class="col-md-3">
        {% bootstrap_field trip_form.beginfieldtrip %}
      </div>
      <div class="col-md-3">
        {% bootstrap_field trip_form.endfieldtrip %}
      </div>
    </div>
    <div class="row">
      <div class="col-md-3">
        {% bootstrap_field trip_form.workers %}
      </div>
      <div class="col-md-3">
        <div id="site-header">
          <label class="control-label" for="id_sites_0">Sites</label>
        </div>
        <div id="site-placeholder">
          Select a field trip location
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        {% bootstrap_field trip_form.note %}
      </div>
    </div>
    <div class="row">
      <div class="form-group">
        <div class="controls ">
          <input type="submit" name="submit" value="Save" class="btn btn-primary" id="submit-id-submit"/>
        </div>
      </div>
    </div>
  </div>
</form>

<script>
$(function(){
  Mustache.tags = ['[[', ']]'];
  var site_template = $('#site-template').html();
  var url_template = '/api/sites/?is_active=1&location=[[location]]&filter_out=cave%20room'
  Mustache.parse(site_template);
  Mustache.parse(url_template);

  $('#id_location').change(function() {
    var val = $(this).val();
    if(val == null || $.trim(val) == "") {
      $('#site-placeholder').empty();
      return;
    }

    var name = $(this).find('option:selected').text();

    $.ajax({
      url: Mustache.render(url_template, {location: name}),
      success: function(data) {
        var rendered = Mustache.render(site_template, {sites: data});
        $('#site-placeholder').html(rendered);
      }
    })
  });
});
</script>
<script id="site-template" type="x-tmpl-mustache">
[[#sites]]
<div class="checkbox">
  <label for="id_selected_sites_[[idsite]]">
    <input id="id_selected_sites_[[idsite]]" name="selected_sites" type="checkbox" value="[[idsite]]"> [[site]]
  </label>
</div>
[[/sites]]
</script>
{% endblock %}

data_collection/templates/new_fieldtrip_sites.html
{% extends 'layouts/base.html' %}
{% block title %}Enter - {{ block.super }}{% endblock %}
{% block content %}
<form action="/new-fieldtrip/select-sites/" method="post">
  {% csrf_token %}
  <div class="container">
    <h4>Sites Sampled</h4>
    {{ sites_form.as_p }}
  </div>
  <input type="submit" value="Submit" />
</form>
{% endblock %}

data_collection/templates/people.html
{% extends 'layouts/base.html' %}
{% block title %}Enter - {{ block.super }}{% endblock %}
{% block content %}
{% load bootstrap3 %}
<form action="/people/" method="post">
 {% csrf_token %}
 <div class="container">
   <div class="row">
     <div class="col-md-3">
       {% bootstrap_field existing_workers.existing_workers %}
     </div>
     <div class="col-md-3">
       <input type="button" name="new_worker" value="Doot" id="id-new-worker"/>
     </div>
   </div>
    <div class="row">
      <input id="id_idworker" name="idworker" class="form-control" type="hidden"/>
      <div class="col-md-3">
        {% bootstrap_field new_worker.workername %}
      </div>
      <div class="col-md-3">
        {% bootstrap_field new_worker.workertype %}
      </div>
      <div class="col-md-3">
        {% bootstrap_field new_worker.affiliation %}
      </div>
      <div class="col-md-3">
        {% bootstrap_field new_worker.jobtitle %}
      </div>
    </div>
    <div class="row">
      <div class="col-md-3">
        {% bootstrap_field new_worker.active %}
      </div>
      <div class="col-md-3">
        {% bootstrap_field new_worker.email %}
      </div>
      <div class="col-md-3">
        {% bootstrap_field new_worker.phonenumber %}
      </div>
    </div>
    <div class="row">
      <div class="form-group">
        <div class="controls ">
          <input type="submit" name="submit" value="Save" class="btn btn-primary" id="submit-id-submit"/>
        </div>
      </div>
    </div>
  </div>
</form>
<script>
$(function(){
  Mustache.tags = ['[[', ']]'];
  var api_target = "/api/workers/[[worker_id]]/";
  Mustache.parse(api_target);
  $('#id_existing_workers').change(function(){
    $.ajax({
      url: Mustache.render(api_target, {worker_id: $(this).val()}),
      success: function(data){
        $.each(data, function(prop, val){
          if(val === true) val = "True";
          if(val === false) val = "False";

          $("#id_" + prop).val(val);
        });
      }
    })

  });


});
</script>
{% endblock %}

data_collection/templates/permission_holder.html
{% extends 'layouts/base.html' %}
{% block title %}Enter - {{ block.super }}{% endblock %}
{% block content %}
{% load data_collection_tags %}
<form action="/permission_holder/" method="post">
    {% csrf_token %}
    Want to put a page here that'll say you don't have permissions to update this stuff, contact Alexandra
{% endblock %}

data_collection/templates/samples_collected.html
{% extends 'layouts/base.html' %}
{% block title %}Enter - {{ block.super }}{% endblock %}
{% block content %}
<form action="/samples-collected/" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit" />
</form>
{% endblock %}

data_collection/templates/success.html
{% extends 'layouts/base.html' %}
{% block title %}Enter - {{ block.super }}{% endblock %}
{% block content %}
<form action="/success/" method="post">
    {% csrf_token %}
    Data entered successfully!
{% endblock %}